language: android

before_install:
    - chmod +x gradlew

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    #- platform-tools
    #- tools

    # The BuildTools version used by your project
    - build-tools-22.0.0

    # The SDK version used to compile your project
    - android-22

    # Additional components
    #- extra
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
    - android-14

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-14
    #- sys-img-armeabi-v7a-android-15
    #- sys-img-armeabi-v7a-android-21
    #- sys-img-armeabi-v7a-android-22
    #- sys-img-armeabi-v7a-android-23
    #- sys-img-x86-android-22

  licenses:
     - 'android-sdk-license-.+'

env:
  global:
    # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=10

before_install:
    - export ANDROID_SERIAL='emulator-5554'

    # Emulator Management: Create, Start and Wait
install:
   - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
   - echo no | android create avd --force -n test1 -t android-14 --abi armeabi-v7a
   - emulator -avd test -no-audio -no-window &
   - emulator -avd test1 -no-audio -no-window &
   - adb wait-for-device get-serialno

before_scrip:
    - ./scripts/wait_for_emulator.sh
    - adb shell input keyevent 82 &
    - ANDROID_SERIAL='emulator-5556'
    - adb wait-for-device get-serialno
    - ./scripts/wait_for_emulator.sh
    - adb shell input keyevent 82 &
    - ANDROID_SERIAL=''
    - adb devices -1

script:
  - android list target
  - adb devices
  - ./gradlew connectedAndroidTest -PdisablePreDex